### ISSUE TITLE
Bang tambah menu nya

### ISSUE THREAD

**Issue by Azex229** [Bintangp02/wabot-aq02#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by unx21** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

hahh??

**Comment by unx21** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

mau kek gimana?

**Comment by Bintangp02** [comment]
> **Apakah permintaan fitur Anda terkait dengan masalah? Tolong jelaskan. **
> Deskripsi yang jelas dan singkat tentang apa masalahnya. Mantan. Saya selalu kecewa ketika [...]
> 
> **Jelaskan solusi yang Anda inginkan**
> Sebuah deskripsi yang jelas dan ringkas tentang apa yang Anda inginkan terjadi.
> 
> **Jelaskan alternatif yang telah Anda pertimbangkan**
> Deskripsi yang jelas dan ringkas tentang solusi atau fitur alternatif apa pun yang telah Anda pertimbangkan.
> 
> **Konteks tambahan**
> Tambahkan konteks atau tangkapan layar lain tentang permintaan fitur di sini.

Run nya kek biasa ya bruh bisa saja di termux atau pun heroku..
Jika anda mau memperjelas ya silahkan pergi ke salah satu YouTube BPBOT
Trimakasih Kabari Saya Jika Eror Trimakasih..
